variable "key_name" {}
variable "public_key" {}
variable "bastion_security_group_id" {}
variable "ami" {}
variable "instance_type" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "availability_zones" {}
variable "associate_public_ip_address" {}
variable "role" {}
variable "environment" {}
