---
- name: "Install Vault"
  include_tasks: install_vault.yml

- name: "Configure vm"
  include_tasks: configure_vm.yml

- name: "Configure Vault Process"
  include_tasks: configure_process.yml

- name: "Start Vault Server"
  include_tasks: start_server.yml
