---
- name: "Check Vault status"
  shell: "export VAULT_ADDR=http://127.0.0.1:8200 && vault status -format=json"
  register: vault_status

- name: "Setting key share"
  shell: "export VAULT_ADDR=http://127.0.0.1:8200 && vault operator init -recovery-shares=5 -recovery-threshold=3"
  register: vault_operator_init
  when:
    - "{{ (vault_status.stdout | from_json).initialized }} == false"

- name: "Printing vault operator init output"
  debug:
    msg: "{{ vault_operator_init }}"
  when:
    - "{{ (vault_status.stdout | from_json).initialized }} == false"
